export interface SongItemType {
  img: string
  name: string
  author: string
  url: string
  id:string
}
//
// export class SongItemType {
//   img: string
//   name: string
//   author: string
//   url: string
//   id: string
//
//   constructor(img: string, name: string, author: string, url: string, id: string) {
//     this.img = img
//     this.name = name
//     this.author = author
//     this.url = url
//     this.id = id
//   }
// }